services:
  api:
    image: ""
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    deploy:
      replicas: 1
    volumes:
      - .:/src:delegated
      - application_obj:/src/Application/obj
      - application_bin:/src/Application/bin
      - unit_tests_obj:/src/UnitTests/obj
      - unit_tests_bin:/src/UnitTests/bin
      - integration_tests_obj:/src/IntegrationTests/obj
      - integration_tests_bin:/src/IntegrationTests/bin
  
  postgres:
    restart: unless-stopped

volumes:
  application_obj:
  application_bin:
  unit_tests_obj:
  unit_tests_bin:
  integration_tests_obj:
  integration_tests_bin:
