services:
  api:
    image: footclash-api-local
    build:
      context: .
      dockerfile: Application/Dockerfile
    deploy:
      replicas: 1
    labels: !override
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.middlewares.api-strip-prefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-strip-prefix"
    volumes:
      - .:/src
      - application_nuget_cache:/root/.nuget/packages
      - application_bin:/src/Application/bin
      - application_obj:/src/Application/obj

  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports: !override
      - "5000:80"
      - "8080:8080"

volumes:
  application_nuget_cache:
  application_bin:
  application_obj:
