name: Restore, Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Restore Solution
        run: dotnet restore ./*.sln

      - name: Build Solution
        run: dotnet build ./*.sln -c Release --no-restore

      - name: Test Solution
        run: dotnet test ./UnitTests/UnitTests.csproj -c Release --no-restore --no-build
